CREATE TABLE `remittance_batches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`weekOf` timestamp NOT NULL,
	`uploadedById` int NOT NULL,
	`totalRemittance` decimal(12,2) NOT NULL DEFAULT '0',
	`totalLines` int NOT NULL DEFAULT 0,
	`matchedLines` int NOT NULL DEFAULT 0,
	`unmatchedLines` int NOT NULL DEFAULT 0,
	`pushedToAgentsAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `remittance_batches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `remittance_lines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batchId` int NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`ptsRef` varchar(100) NOT NULL,
	`returnDate` varchar(50),
	`pax` int,
	`currency` varchar(10) DEFAULT 'GBP',
	`totalIn` decimal(12,2),
	`totalOut` decimal(12,2),
	`sfi` decimal(10,2),
	`safi` decimal(10,2),
	`ptrc` decimal(10,2),
	`pts` decimal(10,2),
	`vatFromPts` decimal(10,2),
	`remittance` decimal(12,2) NOT NULL,
	`vatFromPortal` decimal(10,2),
	`remit80` decimal(12,2),
	`jlt20` decimal(12,2),
	`bookingId` int,
	`agentId` int,
	`agentName` varchar(255),
	`agentEmail` varchar(320),
	`isMatched` boolean NOT NULL DEFAULT false,
	`pushedToAgent` boolean NOT NULL DEFAULT false,
	`pushedAt` timestamp,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `remittance_lines_id` PRIMARY KEY(`id`)
);
