/**
 * External API — CRM Integration
 *
 * POST /api/external/register-booking
 *   Accepts a booking payload from Tom's CRM (or any authorised external system)
 *   and creates a new booking registration in the JLT portal pipeline.
 *
 * Authentication: X-API-Key header containing a raw API key generated by an admin.
 */

import { Router, Request, Response } from "express";
import crypto from "crypto";
import { eq, and } from "drizzle-orm";
import { getDb, createBooking, updateBookingAdminFields, getBookingById } from "./db";
import { apiKeys, users, ssoTokens, agentCrmProfiles } from "../drizzle/schema";

const router = Router();

// ─── Helper: hash a raw API key ──────────────────────────────────────────────

function hashKey(raw: string): string {
  return crypto.createHash("sha256").update(raw).digest("hex");
}

// ─── Helper: validate API key and return the key record ──────────────────────

async function validateApiKey(rawKey: string) {
  const db = await getDb();
  if (!db) return null;
  const hash = hashKey(rawKey);
  const results = await db
    .select()
    .from(apiKeys)
    .where(and(eq(apiKeys.keyHash, hash), eq(apiKeys.isActive, true)))
    .limit(1);
  const key = results[0];
  if (!key) return null;
  // Update lastUsedAt
  await db.update(apiKeys).set({ lastUsedAt: new Date() }).where(eq(apiKeys.id, key.id));
  return key;
}

// ─── POST /api/external/register-booking ─────────────────────────────────────

router.post("/register-booking", async (req: Request, res: Response) => {
  try {
    // 1. Auth
    const rawKey = req.headers["x-api-key"] as string | undefined;
    if (!rawKey) {
      return res.status(401).json({ error: "Missing X-API-Key header" });
    }
    const keyRecord = await validateApiKey(rawKey);
    if (!keyRecord) {
      return res.status(401).json({ error: "Invalid or inactive API key" });
    }

    // 2. Parse body
    const {
      agentEmail,
      clientName,
      departureDate,
      bookedDate,
      destination,
      passengers,
      numberOfNights,
      grossCost,
      expectedCommission,
      orbitMarginPct,
      topdogRef,
      crmRef,
    } = req.body;

    // 3. Validate required fields
    const missing: string[] = [];
    if (!agentEmail) missing.push("agentEmail");
    if (!clientName) missing.push("clientName");
    if (!departureDate) missing.push("departureDate");
    if (!destination) missing.push("destination");
    if (passengers == null) missing.push("passengers");
    if (numberOfNights == null) missing.push("numberOfNights");
    if (grossCost == null) missing.push("grossCost");
    if (missing.length > 0) {
      return res.status(400).json({ error: `Missing required fields: ${missing.join(", ")}` });
    }

    // 4. Resolve agent by email
    const db = await getDb();
    if (!db) return res.status(503).json({ error: "Database unavailable" });

    const normalizedEmail = agentEmail.toLowerCase().trim();
    // First try matching by primary portal email, then fall back to crmEmail alias
    const agentResults = await db
      .select()
      .from(users)
      .where(eq(users.email, normalizedEmail))
      .limit(1);
    let agent = agentResults[0];
    if (!agent) {
      // Try CRM email alias
      const aliasResults = await db
        .select()
        .from(users)
        .where(eq(users.crmEmail, normalizedEmail))
        .limit(1);
      agent = aliasResults[0];
    }
    if (!agent) {
      return res.status(404).json({
        error: `No agent account found with email: ${agentEmail}. Please ensure the agent is registered on the JLT portal, or ask them to set their CRM email alias in their profile.`,
      });
    }
    if (agent.role !== "agent" && agent.role !== "admin" && agent.role !== "super_admin") {
      return res.status(403).json({ error: "The account associated with this email is not an agent account." });
    }

    // 5. Parse dates
    const parsedDepartureDate = new Date(departureDate);
    if (isNaN(parsedDepartureDate.getTime())) {
      return res.status(400).json({ error: "Invalid departureDate — expected ISO 8601 format (e.g. 2026-08-15)" });
    }
    const parsedBookedDate = bookedDate ? new Date(bookedDate) : new Date();
    if (bookedDate && isNaN(parsedBookedDate.getTime())) {
      return res.status(400).json({ error: "Invalid bookedDate — expected ISO 8601 format (e.g. 2026-04-01)" });
    }

    // 6. Parse numbers
    const parsedPassengers = parseInt(String(passengers), 10);
    const parsedNights = parseInt(String(numberOfNights), 10);
    const parsedGross = parseFloat(String(grossCost));
    const parsedCommission = expectedCommission != null ? parseFloat(String(expectedCommission)) : undefined;
    const parsedMarginPct = orbitMarginPct != null ? parseFloat(String(orbitMarginPct)) : undefined;

    if (isNaN(parsedPassengers) || parsedPassengers < 1) {
      return res.status(400).json({ error: "passengers must be a positive integer" });
    }
    if (isNaN(parsedNights) || parsedNights < 0) {
      return res.status(400).json({ error: "numberOfNights must be a non-negative integer" });
    }
    if (isNaN(parsedGross) || parsedGross <= 0) {
      return res.status(400).json({ error: "grossCost must be a positive number" });
    }

    // 7. Create the booking
    const booking = await createBooking({
      agentId: agent.id,
      clientName: String(clientName).trim(),
      departureDate: parsedDepartureDate,
      bookedDate: parsedBookedDate,
      destination: String(destination).trim(),
      passengers: parsedPassengers,
      numberOfNights: parsedNights,
      grossCost: parsedGross,
      expectedCommission: parsedCommission,
      topdogRef: topdogRef ? String(topdogRef).trim() : undefined,
      crmRef: crmRef ? String(crmRef).trim() : undefined,
      reimbursementsRequired: false,
      orbitMarginPct: parsedMarginPct,
    });

    if (!booking) {
      return res.status(500).json({ error: "Failed to create booking" });
    }

    // 10. Return success
    const portalUrl = `https://portal.thejltgroup.co.uk/bookings/${booking.id}`;
    return res.status(201).json({
      success: true,
      bookingId: booking.id,
      portalUrl,
      clientName: booking.clientName,
      currentStage: "New Booking",
      message: `Booking registered successfully. View at ${portalUrl}`,
    });
  } catch (err: any) {
    console.error("[external-api] register-booking error:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── POST /api/external/update-commission ────────────────────────────────────
/**
 * Update the expectedCommission on an existing booking.
 * Called by Tom's CRM when the agent clicks "Send Expected Commission".
 *
 * Body: { bookingId?, crmRef?, expectedCommission, agentEmail? }
 * At least one of bookingId or crmRef must be provided.
 */
router.post("/update-commission", async (req: Request, res: Response) => {
  try {
    // 1. Auth
    const rawKey = req.headers["x-api-key"] as string | undefined;
    if (!rawKey) return res.status(401).json({ error: "Missing X-API-Key header" });
    const keyRecord = await validateApiKey(rawKey);
    if (!keyRecord) return res.status(401).json({ error: "Invalid or inactive API key" });

    // 2. Parse body
    const { bookingId, crmRef, expectedCommission, orbitMarginPct, agentEmail } = req.body;

    // 3. Validate
    if (bookingId == null && !crmRef) {
      return res.status(400).json({ error: "Provide at least one of bookingId or crmRef to identify the booking" });
    }
    if (expectedCommission == null) {
      return res.status(400).json({ error: "Missing required field: expectedCommission" });
    }
    const parsedCommission = parseFloat(String(expectedCommission));
    if (isNaN(parsedCommission) || parsedCommission < 0) {
      return res.status(400).json({ error: "expectedCommission must be a non-negative number" });
    }

    // 4. Resolve booking
    const db = await getDb();
    if (!db) return res.status(503).json({ error: "Database unavailable" });

    const { bookings: bookingsTable } = await import("../drizzle/schema");
    let booking;
    if (bookingId != null) {
      booking = await getBookingById(Number(bookingId));
    } else {
      const results = await db
        .select()
        .from(bookingsTable)
        .where(eq(bookingsTable.crmRef, String(crmRef).trim()))
        .limit(1);
      booking = results[0];
    }

    if (!booking) {
      return res.status(404).json({
        error: bookingId != null
          ? `No booking found with id: ${bookingId}`
          : `No booking found with crmRef: ${crmRef}`,
      });
    }

    // 5. Optional: verify agentEmail matches the booking's agent (security check)
    if (agentEmail) {
      const normalizedEmail = String(agentEmail).toLowerCase().trim();
      const agentResults = await db
        .select()
        .from(users)
        .where(eq(users.id, booking.agentId))
        .limit(1);
      const agent = agentResults[0];
      if (agent) {
        const portalEmail = (agent.email ?? "").toLowerCase();
        const crmAliasEmail = ((agent as any).crmEmail ?? "").toLowerCase();
        if (portalEmail !== normalizedEmail && crmAliasEmail !== normalizedEmail) {
          return res.status(403).json({
            error: `The agentEmail provided (${agentEmail}) does not match the agent assigned to this booking.`,
          });
        }
      }
    }

    // 6. Update
    const updateFields: Record<string, any> = { expectedCommission: parsedCommission };
    if (orbitMarginPct != null) {
      const parsedMarginPct = parseFloat(String(orbitMarginPct));
      if (!isNaN(parsedMarginPct) && parsedMarginPct >= 0) {
        updateFields.orbitMarginPct = parsedMarginPct;
      }
    }
    await updateBookingAdminFields(booking.id, updateFields);

    return res.status(200).json({ success: true, bookingId: booking.id, expectedCommission: parsedCommission, orbitMarginPct: updateFields.orbitMarginPct ?? null });
  } catch (err: any) {
    console.error("[external-api] update-commission error:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── GET /api/external/sso/verify ───────────────────────────────────────────
/**
 * Tom's CRM calls this to verify a magic link token and get the agent's details.
 * The token is single-use and expires after 90 seconds.
 *
 * Query param: ?token=<token>
 * Returns: { valid: true, userId, email, name, role } or { valid: false, error }
 */
router.get("/sso/verify", async (req: Request, res: Response) => {
  try {
    const { token } = req.query as { token?: string };
    if (!token) return res.status(400).json({ valid: false, error: "Missing token parameter" });

    const db = await getDb();
    if (!db) return res.status(503).json({ valid: false, error: "Database unavailable" });

    // Find token
    const results = await db
      .select()
      .from(ssoTokens)
      .where(eq(ssoTokens.token, token))
      .limit(1);
    const record = results[0];

    if (!record) return res.status(404).json({ valid: false, error: "Token not found" });
    if (record.usedAt) return res.status(410).json({ valid: false, error: "Token already used" });
    if (new Date() > record.expiresAt) return res.status(410).json({ valid: false, error: "Token expired" });

    // Mark as used
    await db.update(ssoTokens).set({ usedAt: new Date() }).where(eq(ssoTokens.id, record.id));

    // Get agent details
    const agentResults = await db
      .select({ id: users.id, email: users.email, name: users.name, role: users.role, phone: users.phone })
      .from(users)
      .where(eq(users.id, record.userId))
      .limit(1);
    const agent = agentResults[0];
    if (!agent) return res.status(404).json({ valid: false, error: "Agent not found" });

    // Get Agent ID (JLT-XXXX) from CRM profile so Orbit can link the account
    const profileResults = await db
      .select({ uniqueAgentId: agentCrmProfiles.uniqueAgentId })
      .from(agentCrmProfiles)
      .where(eq(agentCrmProfiles.userId, record.userId))
      .limit(1);
    const uniqueAgentId = profileResults[0]?.uniqueAgentId ?? null;

    return res.status(200).json({
      valid: true,
      userId: agent.id,
      email: agent.email,
      name: agent.name,
      role: agent.role,
      phone: agent.phone ?? null,
      uniqueAgentId,
    });
  } catch (err: any) {
    console.error("[external-api] sso/verify error:", err);
    return res.status(500).json({ valid: false, error: "Internal server error" });
  }
});

// ─── Commission status helpers ──────────────────────────────────────────────

/**
 * Map portal claim status → Orbit's expected enum.
 * A booking with no claim record returns "unclaimed".
 */
function toOrbitStatus(
  portalStatus: string | null | undefined,
  bookingStage?: string | null
): string {
  // If there's an active claim, send the exact portal claim status
  if (portalStatus) {
    switch (portalStatus) {
      case "paid":             return "paid";
      case "awaiting_payment": return "awaiting_payment";
      case "top_up_required":  return "top_up_required";
      case "notice_hold":      return "notice_hold";
      case "processing":       return "processing";
      case "pending":          return "pending";
      default:                 return "pending";
    }
  }
  // No claim yet — check if the booking is at the Commission Claimable stage
  if (bookingStage === "Commission Claimable") return "claimable";
  return "unclaimed";
}

/**
 * Build the response object for a single booking + its latest claim.
 */
function buildCommissionStatusRow(booking: any, claim: any | null) {
  return {
    bookingId:     booking.id,
    crmRef:        booking.crmRef ?? null,
    claimStatus:   toOrbitStatus(claim?.status, booking.currentStage),
    claimedAmount: claim?.grossAmount != null ? parseFloat(claim.grossAmount) : null,
    claimedAt:     claim?.claimedAt ? new Date(claim.claimedAt).toISOString() : null,
    paidAt:        claim?.paidAt    ? new Date(claim.paidAt).toISOString()    : null,
    updatedAt:     claim?.updatedAt ? new Date(claim.updatedAt).toISOString() : new Date(booking.updatedAt).toISOString(),
    notes:         claim?.topUpNote ?? null,
  };
}

// ─── GET /api/external/commission-status ─────────────────────────────────────
/**
 * Return the commission claim status for a single booking.
 * Orbit passes ?crmRef=JLT-001  OR  ?bookingId=1234
 */
router.get("/commission-status", async (req: Request, res: Response) => {
  try {
    const rawKey = req.headers["x-api-key"] as string | undefined;
    if (!rawKey) return res.status(401).json({ error: "Missing X-API-Key header" });
    const keyRecord = await validateApiKey(rawKey);
    if (!keyRecord) return res.status(401).json({ error: "Invalid or inactive API key" });

    const { crmRef, bookingId } = req.query as { crmRef?: string; bookingId?: string };
    if (!crmRef && !bookingId) {
      return res.status(400).json({ error: "Provide at least one of crmRef or bookingId" });
    }

    const db = await getDb();
    if (!db) return res.status(503).json({ error: "Database unavailable" });

    const { bookings: bookingsTable, commissionClaims } = await import("../drizzle/schema");
    const { desc } = await import("drizzle-orm");

    // Resolve booking
    let booking: any;
    if (bookingId != null) {
      const rows = await db.select().from(bookingsTable).where(eq(bookingsTable.id, Number(bookingId))).limit(1);
      booking = rows[0];
    } else {
      const rows = await db.select().from(bookingsTable).where(eq(bookingsTable.crmRef, String(crmRef).trim())).limit(1);
      booking = rows[0];
    }

    if (!booking) {
      return res.status(404).json({
        error: bookingId != null
          ? `No booking found with bookingId: ${bookingId}`
          : `No booking found with crmRef: ${crmRef}`,
      });
    }

    // Get latest claim for this booking (most recently updated)
    const claims = await db
      .select()
      .from(commissionClaims)
      .where(eq(commissionClaims.bookingId, booking.id))
      .orderBy(desc(commissionClaims.updatedAt))
      .limit(1);
    const claim = claims[0] ?? null;

    return res.status(200).json(buildCommissionStatusRow(booking, claim));
  } catch (err: any) {
    console.error("[external-api] commission-status error:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── GET /api/external/commission-status/bulk ────────────────────────────────
/**
 * Return paginated commission claim statuses for all bookings.
 * Supports ?updatedSince=ISO8601  ?page=1  ?pageSize=100 (max 500)
 */
router.get("/commission-status/bulk", async (req: Request, res: Response) => {
  try {
    const rawKey = req.headers["x-api-key"] as string | undefined;
    if (!rawKey) return res.status(401).json({ error: "Missing X-API-Key header" });
    const keyRecord = await validateApiKey(rawKey);
    if (!keyRecord) return res.status(401).json({ error: "Invalid or inactive API key" });

    const {
      updatedSince,
      page: pageStr = "1",
      pageSize: pageSizeStr = "100",
    } = req.query as { updatedSince?: string; page?: string; pageSize?: string };

    const page     = Math.max(1, parseInt(pageStr, 10) || 1);
    const pageSize = Math.min(500, Math.max(1, parseInt(pageSizeStr, 10) || 100));
    const offset   = (page - 1) * pageSize;

    const db = await getDb();
    if (!db) return res.status(503).json({ error: "Database unavailable" });

    const { bookings: bookingsTable, commissionClaims } = await import("../drizzle/schema");
    const { gte, desc, sql: drizzleSql } = await import("drizzle-orm");

    // Build WHERE clause for updatedSince (applies to both bookings and claims)
    let sinceDate: Date | null = null;
    if (updatedSince) {
      sinceDate = new Date(updatedSince);
      if (isNaN(sinceDate.getTime())) {
        return res.status(400).json({ error: "Invalid updatedSince — expected ISO 8601 datetime (e.g. 2026-06-01T00:00:00Z)" });
      }
    }

    // Fetch all bookings (optionally filtered by updatedSince on the booking row)
    const bookingQuery = db
      .select()
      .from(bookingsTable)
      .orderBy(desc(bookingsTable.updatedAt));

    const allBookings: any[] = sinceDate
      ? await (bookingQuery.where(gte(bookingsTable.updatedAt, sinceDate)) as any)
      : await (bookingQuery as any);

    const total = allBookings.length;
    const pageBookings = allBookings.slice(offset, offset + pageSize);

    if (pageBookings.length === 0) {
      return res.status(200).json({ total, page, pageSize, results: [] });
    }

    // Fetch latest claim for each booking in one query
    const bookingIds = pageBookings.map((b: any) => b.id);
    const { inArray } = await import("drizzle-orm");
    const allClaims: any[] = await db
      .select()
      .from(commissionClaims)
      .where(inArray(commissionClaims.bookingId, bookingIds))
      .orderBy(desc(commissionClaims.updatedAt));

    // Keep only the latest claim per booking
    const latestClaimByBooking = new Map<number, any>();
    for (const claim of allClaims) {
      if (!latestClaimByBooking.has(claim.bookingId)) {
        latestClaimByBooking.set(claim.bookingId, claim);
      }
    }

    const results = pageBookings.map((b: any) =>
      buildCommissionStatusRow(b, latestClaimByBooking.get(b.id) ?? null)
    );

    return res.status(200).json({ total, page, pageSize, results });
  } catch (err: any) {
    console.error("[external-api] commission-status/bulk error:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── Export ───────────────────────────────────────────────────────────────────

export { router as externalApiRouter, hashKey };
