/**
 * External API — CRM Integration
 *
 * POST /api/external/register-booking
 *   Accepts a booking payload from Tom's CRM (or any authorised external system)
 *   and creates a new booking registration in the JLT portal pipeline.
 *
 * Authentication: X-API-Key header containing a raw API key generated by an admin.
 */

import { Router, Request, Response } from "express";
import crypto from "crypto";
import { eq, and } from "drizzle-orm";
import { getDb, createBooking, updateBookingAdminFields, getBookingById } from "./db";
import { apiKeys, users, ssoTokens } from "../drizzle/schema";

const router = Router();

// ─── Helper: hash a raw API key ──────────────────────────────────────────────

function hashKey(raw: string): string {
  return crypto.createHash("sha256").update(raw).digest("hex");
}

// ─── Helper: validate API key and return the key record ──────────────────────

async function validateApiKey(rawKey: string) {
  const db = await getDb();
  if (!db) return null;
  const hash = hashKey(rawKey);
  const results = await db
    .select()
    .from(apiKeys)
    .where(and(eq(apiKeys.keyHash, hash), eq(apiKeys.isActive, true)))
    .limit(1);
  const key = results[0];
  if (!key) return null;
  // Update lastUsedAt
  await db.update(apiKeys).set({ lastUsedAt: new Date() }).where(eq(apiKeys.id, key.id));
  return key;
}

// ─── POST /api/external/register-booking ─────────────────────────────────────

router.post("/register-booking", async (req: Request, res: Response) => {
  try {
    // 1. Auth
    const rawKey = req.headers["x-api-key"] as string | undefined;
    if (!rawKey) {
      return res.status(401).json({ error: "Missing X-API-Key header" });
    }
    const keyRecord = await validateApiKey(rawKey);
    if (!keyRecord) {
      return res.status(401).json({ error: "Invalid or inactive API key" });
    }

    // 2. Parse body
    const {
      agentEmail,
      clientName,
      departureDate,
      bookedDate,
      destination,
      passengers,
      numberOfNights,
      grossCost,
      expectedCommission,
      topdogRef,
      crmRef,
    } = req.body;

    // 3. Validate required fields
    const missing: string[] = [];
    if (!agentEmail) missing.push("agentEmail");
    if (!clientName) missing.push("clientName");
    if (!departureDate) missing.push("departureDate");
    if (!destination) missing.push("destination");
    if (passengers == null) missing.push("passengers");
    if (numberOfNights == null) missing.push("numberOfNights");
    if (grossCost == null) missing.push("grossCost");
    if (missing.length > 0) {
      return res.status(400).json({ error: `Missing required fields: ${missing.join(", ")}` });
    }

    // 4. Resolve agent by email
    const db = await getDb();
    if (!db) return res.status(503).json({ error: "Database unavailable" });

    const normalizedEmail = agentEmail.toLowerCase().trim();
    // First try matching by primary portal email, then fall back to crmEmail alias
    const agentResults = await db
      .select()
      .from(users)
      .where(eq(users.email, normalizedEmail))
      .limit(1);
    let agent = agentResults[0];
    if (!agent) {
      // Try CRM email alias
      const aliasResults = await db
        .select()
        .from(users)
        .where(eq(users.crmEmail, normalizedEmail))
        .limit(1);
      agent = aliasResults[0];
    }
    if (!agent) {
      return res.status(404).json({
        error: `No agent account found with email: ${agentEmail}. Please ensure the agent is registered on the JLT portal, or ask them to set their CRM email alias in their profile.`,
      });
    }
    if (agent.role !== "agent" && agent.role !== "admin" && agent.role !== "super_admin") {
      return res.status(403).json({ error: "The account associated with this email is not an agent account." });
    }

    // 5. Parse dates
    const parsedDepartureDate = new Date(departureDate);
    if (isNaN(parsedDepartureDate.getTime())) {
      return res.status(400).json({ error: "Invalid departureDate — expected ISO 8601 format (e.g. 2026-08-15)" });
    }
    const parsedBookedDate = bookedDate ? new Date(bookedDate) : new Date();
    if (bookedDate && isNaN(parsedBookedDate.getTime())) {
      return res.status(400).json({ error: "Invalid bookedDate — expected ISO 8601 format (e.g. 2026-04-01)" });
    }

    // 6. Parse numbers
    const parsedPassengers = parseInt(String(passengers), 10);
    const parsedNights = parseInt(String(numberOfNights), 10);
    const parsedGross = parseFloat(String(grossCost));
    const parsedCommission = expectedCommission != null ? parseFloat(String(expectedCommission)) : undefined;

    if (isNaN(parsedPassengers) || parsedPassengers < 1) {
      return res.status(400).json({ error: "passengers must be a positive integer" });
    }
    if (isNaN(parsedNights) || parsedNights < 0) {
      return res.status(400).json({ error: "numberOfNights must be a non-negative integer" });
    }
    if (isNaN(parsedGross) || parsedGross <= 0) {
      return res.status(400).json({ error: "grossCost must be a positive number" });
    }

    // 7. Create the booking
    const booking = await createBooking({
      agentId: agent.id,
      clientName: String(clientName).trim(),
      departureDate: parsedDepartureDate,
      bookedDate: parsedBookedDate,
      destination: String(destination).trim(),
      passengers: parsedPassengers,
      numberOfNights: parsedNights,
      grossCost: parsedGross,
      expectedCommission: parsedCommission,
      topdogRef: topdogRef ? String(topdogRef).trim() : undefined,
      crmRef: crmRef ? String(crmRef).trim() : undefined,
      reimbursementsRequired: false,
    });

    if (!booking) {
      return res.status(500).json({ error: "Failed to create booking" });
    }

    // 10. Return success
    const portalUrl = `https://portal.thejltgroup.co.uk/bookings/${booking.id}`;
    return res.status(201).json({
      success: true,
      bookingId: booking.id,
      portalUrl,
      clientName: booking.clientName,
      currentStage: "New Booking",
      message: `Booking registered successfully. View at ${portalUrl}`,
    });
  } catch (err: any) {
    console.error("[external-api] register-booking error:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── POST /api/external/update-commission ────────────────────────────────────
/**
 * Update the expectedCommission on an existing booking.
 * Called by Tom's CRM when the agent clicks "Send Expected Commission".
 *
 * Body: { bookingId?, crmRef?, expectedCommission, agentEmail? }
 * At least one of bookingId or crmRef must be provided.
 */
router.post("/update-commission", async (req: Request, res: Response) => {
  try {
    // 1. Auth
    const rawKey = req.headers["x-api-key"] as string | undefined;
    if (!rawKey) return res.status(401).json({ error: "Missing X-API-Key header" });
    const keyRecord = await validateApiKey(rawKey);
    if (!keyRecord) return res.status(401).json({ error: "Invalid or inactive API key" });

    // 2. Parse body
    const { bookingId, crmRef, expectedCommission, agentEmail } = req.body;

    // 3. Validate
    if (bookingId == null && !crmRef) {
      return res.status(400).json({ error: "Provide at least one of bookingId or crmRef to identify the booking" });
    }
    if (expectedCommission == null) {
      return res.status(400).json({ error: "Missing required field: expectedCommission" });
    }
    const parsedCommission = parseFloat(String(expectedCommission));
    if (isNaN(parsedCommission) || parsedCommission < 0) {
      return res.status(400).json({ error: "expectedCommission must be a non-negative number" });
    }

    // 4. Resolve booking
    const db = await getDb();
    if (!db) return res.status(503).json({ error: "Database unavailable" });

    const { bookings: bookingsTable } = await import("../drizzle/schema");
    let booking;
    if (bookingId != null) {
      booking = await getBookingById(Number(bookingId));
    } else {
      const results = await db
        .select()
        .from(bookingsTable)
        .where(eq(bookingsTable.crmRef, String(crmRef).trim()))
        .limit(1);
      booking = results[0];
    }

    if (!booking) {
      return res.status(404).json({
        error: bookingId != null
          ? `No booking found with id: ${bookingId}`
          : `No booking found with crmRef: ${crmRef}`,
      });
    }

    // 5. Optional: verify agentEmail matches the booking's agent (security check)
    if (agentEmail) {
      const normalizedEmail = String(agentEmail).toLowerCase().trim();
      const agentResults = await db
        .select()
        .from(users)
        .where(eq(users.id, booking.agentId))
        .limit(1);
      const agent = agentResults[0];
      if (agent) {
        const portalEmail = (agent.email ?? "").toLowerCase();
        const crmAliasEmail = ((agent as any).crmEmail ?? "").toLowerCase();
        if (portalEmail !== normalizedEmail && crmAliasEmail !== normalizedEmail) {
          return res.status(403).json({
            error: `The agentEmail provided (${agentEmail}) does not match the agent assigned to this booking.`,
          });
        }
      }
    }

    // 6. Update
    await updateBookingAdminFields(booking.id, { expectedCommission: parsedCommission });

    return res.status(200).json({ success: true, bookingId: booking.id, expectedCommission: parsedCommission });
  } catch (err: any) {
    console.error("[external-api] update-commission error:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── GET /api/external/sso/verify ───────────────────────────────────────────
/**
 * Tom's CRM calls this to verify a magic link token and get the agent's details.
 * The token is single-use and expires after 90 seconds.
 *
 * Query param: ?token=<token>
 * Returns: { valid: true, userId, email, name, role } or { valid: false, error }
 */
router.get("/sso/verify", async (req: Request, res: Response) => {
  try {
    const { token } = req.query as { token?: string };
    if (!token) return res.status(400).json({ valid: false, error: "Missing token parameter" });

    const db = await getDb();
    if (!db) return res.status(503).json({ valid: false, error: "Database unavailable" });

    // Find token
    const results = await db
      .select()
      .from(ssoTokens)
      .where(eq(ssoTokens.token, token))
      .limit(1);
    const record = results[0];

    if (!record) return res.status(404).json({ valid: false, error: "Token not found" });
    if (record.usedAt) return res.status(410).json({ valid: false, error: "Token already used" });
    if (new Date() > record.expiresAt) return res.status(410).json({ valid: false, error: "Token expired" });

    // Mark as used
    await db.update(ssoTokens).set({ usedAt: new Date() }).where(eq(ssoTokens.id, record.id));

    // Get agent details
    const agentResults = await db
      .select({ id: users.id, email: users.email, name: users.name, role: users.role, phone: users.phone })
      .from(users)
      .where(eq(users.id, record.userId))
      .limit(1);
    const agent = agentResults[0];
    if (!agent) return res.status(404).json({ valid: false, error: "Agent not found" });

    return res.status(200).json({
      valid: true,
      userId: agent.id,
      email: agent.email,
      name: agent.name,
      role: agent.role,
      phone: agent.phone ?? null,
    });
  } catch (err: any) {
    console.error("[external-api] sso/verify error:", err);
    return res.status(500).json({ valid: false, error: "Internal server error" });
  }
});

// ─── Export ───────────────────────────────────────────────────────────────────

export { router as externalApiRouter, hashKey };
