/**
 * External API — CRM Integration
 *
 * POST /api/external/register-booking
 *   Accepts a booking payload from Tom's CRM (or any authorised external system)
 *   and creates a new booking registration in the JLT portal pipeline.
 *
 * Authentication: X-API-Key header containing a raw API key generated by an admin.
 */

import { Router, Request, Response } from "express";
import crypto from "crypto";
import { eq, and } from "drizzle-orm";
import { getDb, createBooking } from "./db";
import { apiKeys, users } from "../drizzle/schema";

const router = Router();

// ─── Helper: hash a raw API key ──────────────────────────────────────────────

function hashKey(raw: string): string {
  return crypto.createHash("sha256").update(raw).digest("hex");
}

// ─── Helper: validate API key and return the key record ──────────────────────

async function validateApiKey(rawKey: string) {
  const db = await getDb();
  if (!db) return null;
  const hash = hashKey(rawKey);
  const results = await db
    .select()
    .from(apiKeys)
    .where(and(eq(apiKeys.keyHash, hash), eq(apiKeys.isActive, true)))
    .limit(1);
  const key = results[0];
  if (!key) return null;
  // Update lastUsedAt
  await db.update(apiKeys).set({ lastUsedAt: new Date() }).where(eq(apiKeys.id, key.id));
  return key;
}

// ─── POST /api/external/register-booking ─────────────────────────────────────

router.post("/register-booking", async (req: Request, res: Response) => {
  try {
    // 1. Auth
    const rawKey = req.headers["x-api-key"] as string | undefined;
    if (!rawKey) {
      return res.status(401).json({ error: "Missing X-API-Key header" });
    }
    const keyRecord = await validateApiKey(rawKey);
    if (!keyRecord) {
      return res.status(401).json({ error: "Invalid or inactive API key" });
    }

    // 2. Parse body
    const {
      agentEmail,
      clientName,
      departureDate,
      bookedDate,
      destination,
      passengers,
      numberOfNights,
      grossCost,
      expectedCommission,
      topdogRef,
      crmRef,
    } = req.body;

    // 3. Validate required fields
    const missing: string[] = [];
    if (!agentEmail) missing.push("agentEmail");
    if (!clientName) missing.push("clientName");
    if (!departureDate) missing.push("departureDate");
    if (!destination) missing.push("destination");
    if (passengers == null) missing.push("passengers");
    if (numberOfNights == null) missing.push("numberOfNights");
    if (grossCost == null) missing.push("grossCost");
    if (missing.length > 0) {
      return res.status(400).json({ error: `Missing required fields: ${missing.join(", ")}` });
    }

    // 4. Resolve agent by email
    const db = await getDb();
    if (!db) return res.status(503).json({ error: "Database unavailable" });

    const agentResults = await db
      .select()
      .from(users)
      .where(eq(users.email, agentEmail.toLowerCase().trim()))
      .limit(1);
    const agent = agentResults[0];
    if (!agent) {
      return res.status(404).json({
        error: `No agent account found with email: ${agentEmail}. Please ensure the agent is registered on the JLT portal.`,
      });
    }
    if (agent.role !== "agent" && agent.role !== "admin" && agent.role !== "super_admin") {
      return res.status(403).json({ error: "The account associated with this email is not an agent account." });
    }

    // 5. Parse dates
    const parsedDepartureDate = new Date(departureDate);
    if (isNaN(parsedDepartureDate.getTime())) {
      return res.status(400).json({ error: "Invalid departureDate — expected ISO 8601 format (e.g. 2026-08-15)" });
    }
    const parsedBookedDate = bookedDate ? new Date(bookedDate) : new Date();
    if (bookedDate && isNaN(parsedBookedDate.getTime())) {
      return res.status(400).json({ error: "Invalid bookedDate — expected ISO 8601 format (e.g. 2026-04-01)" });
    }

    // 6. Parse numbers
    const parsedPassengers = parseInt(String(passengers), 10);
    const parsedNights = parseInt(String(numberOfNights), 10);
    const parsedGross = parseFloat(String(grossCost));
    const parsedCommission = expectedCommission != null ? parseFloat(String(expectedCommission)) : undefined;

    if (isNaN(parsedPassengers) || parsedPassengers < 1) {
      return res.status(400).json({ error: "passengers must be a positive integer" });
    }
    if (isNaN(parsedNights) || parsedNights < 0) {
      return res.status(400).json({ error: "numberOfNights must be a non-negative integer" });
    }
    if (isNaN(parsedGross) || parsedGross <= 0) {
      return res.status(400).json({ error: "grossCost must be a positive number" });
    }

    // 7. Create the booking
    const booking = await createBooking({
      agentId: agent.id,
      clientName: String(clientName).trim(),
      departureDate: parsedDepartureDate,
      bookedDate: parsedBookedDate,
      destination: String(destination).trim(),
      passengers: parsedPassengers,
      numberOfNights: parsedNights,
      grossCost: parsedGross,
      expectedCommission: parsedCommission,
      topdogRef: topdogRef ? String(topdogRef).trim() : undefined,
      crmRef: crmRef ? String(crmRef).trim() : undefined,
      reimbursementsRequired: false,
    });

    if (!booking) {
      return res.status(500).json({ error: "Failed to create booking" });
    }

    // 10. Return success
    const portalUrl = `https://portal.thejltgroup.co.uk/bookings/${booking.id}`;
    return res.status(201).json({
      success: true,
      bookingId: booking.id,
      portalUrl,
      clientName: booking.clientName,
      currentStage: "New Booking",
      message: `Booking registered successfully. View at ${portalUrl}`,
    });
  } catch (err: any) {
    console.error("[external-api] register-booking error:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── Export ───────────────────────────────────────────────────────────────────

export { router as externalApiRouter, hashKey };
